#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nubia/nx563j

PRODUCT_COPY_FILES += \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-00-01.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-00-01.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-00-02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-00-02.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-00-03.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-00-03.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-00-04.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-00-04.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-01-01.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-01-01.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-01-02.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-01-02.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-01-03.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-01-03.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/.tp/.thermal-mode-01-04.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal-mode-01-04.conf \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/nubia/nx563j/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/nubia/nx563j/proprietary/vendor/etc/camera/imx318_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx318_chromatix.xml \
    vendor/nubia/nx563j/proprietary/vendor/etc/camera/imx362_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/imx362_chromatix.xml \
    vendor/nubia/nx563j/proprietary/vendor/etc/camera/s5k3p3_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k3p3_chromatix.xml \
    vendor/nubia/nx563j/proprietary/vendor/etc/firmware/SCTable.asb:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/SCTable.asb \
    vendor/nubia/nx563j/proprietary/vendor/etc/firmware/TBM_D2.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/TBM_D2.bin \
    vendor/nubia/nx563j/proprietary/vendor/etc/firmware/miniBoot.bin:$(TARGET_COPY_OUT_VENDOR)/etc/firmware/miniBoot.bin \
    vendor/nubia/nx563j/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint.fpc@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint.fpc@2.1-service.rc \
    vendor/nubia/nx563j/proprietary/vendor/etc/libnfc-brcm-20797b00.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-brcm-20797b00.conf \
    vendor/nubia/nx563j/proprietary/vendor/firmware/BCM20797A1_001.002.015.2562.0011_Generic_I2C_NCD_Unsigned_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20797A1_001.002.015.2562.0011_Generic_I2C_NCD_Unsigned_configdata.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/BCM20797B0_002.001.043.2562.0007_Generic_I2C_NCD_Unsigned_BCM20797B0_002.001.043.2562.0007_I2C_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20797B0_002.001.043.2562.0007_Generic_I2C_NCD_Unsigned_BCM20797B0_002.001.043.2562.0007_I2C_configdata.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/BCM20797B0_002.001.043.2562.0010_Generic_I2C_NCD_Unsigned_BCM20797B0_002.001.043.2562.0010_I2C_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20797B0_002.001.043.2562.0010_Generic_I2C_NCD_Unsigned_BCM20797B0_002.001.043.2562.0010_I2C_configdata.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/BCM20797B0_002.001.043.2564.0002_Generic_NCD_Unsigned_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20797B0_002.001.043.2564.0002_Generic_NCD_Unsigned_configdata.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/BCM20797B0_002.001.043.2565.0005_Generic_NCD_Unsigned_configdata.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/BCM20797B0_002.001.043.2565.0005_Generic_NCD_Unsigned_configdata.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_1021_1.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_1021_1.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_119_1.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_119_1.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_222_1.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_222_1.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_512_3.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_512_3.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_706.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_706.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_822_2.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_822_2.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_918_1.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_918_1.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_SY.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_SY.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/Generic_unsigned_fix_p2p_stuck.ncd:$(TARGET_COPY_OUT_VENDOR)/firmware/Generic_unsigned_fix_p2p_stuck.ncd \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/nubia/nx563j/proprietary/vendor/firmware/nubia_tp_jdi_fw.img:$(TARGET_COPY_OUT_VENDOR)/firmware/nubia_tp_jdi_fw.img \
    vendor/nubia/nx563j/proprietary/vendor/firmware/tas2555_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2555_uCDSP.bin

PRODUCT_PACKAGES += \
    consumerir.msm8998 \
    libNubiaImageAlgorithm \
    libalParseOTP \
    libalRnB \
    libalSDE2 \
    libalSPE \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_image_algorithm \
    libarcsoft_beautyshot_video_algorithm \
    libarcsoft_dualcam_refocus \
    libarcsoft_low_light_shot \
    libarcsoft_night_shot \
    libmmcamera2_frame_algorithm \
    libmmcamera2_is \
    libmmcamera2_q3a_core \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera_dbg \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmpbase \
    libnubia_effect \
    camera.msm8998 \
    libAltek_AF \
    libHAFIAFalSDE1 \
    libIAFalSDE1 \
    libIQ_Match_Lib \
    libSonyIMX318PdafLibrary \
    libactuator_ak7371 \
    libactuator_ak7371_aux \
    libalCMotion \
    libalSDK \
    libarcsoft_high_dynamic_range \
    libarcsoft_picauto \
    libchromatix_imx318_1080p_preview_3a \
    libchromatix_imx318_1080p_video_3a \
    libchromatix_imx318_4k_preview_3a \
    libchromatix_imx318_4k_video_3a \
    libchromatix_imx318_a3_3dtest_mode \
    libchromatix_imx318_a3_arcsoft_bokeh \
    libchromatix_imx318_a3_bokeh_mode \
    libchromatix_imx318_a3_elec_aper_hand \
    libchromatix_imx318_a3_electron_aperture \
    libchromatix_imx318_a3_iso128_preview \
    libchromatix_imx318_a3_iso128_preview_dng \
    libchromatix_imx318_a3_light_painting \
    libchromatix_imx318_a3_panorama \
    libchromatix_imx318_a3_profession_mode \
    libchromatix_imx318_a3_startrack \
    libchromatix_imx318_arcsoft_bokeh \
    libchromatix_imx318_bokeh \
    libchromatix_imx318_common \
    libchromatix_imx318_common_bokeh \
    libchromatix_imx318_common_dng \
    libchromatix_imx318_common_iso128 \
    libchromatix_imx318_common_iso128_dng \
    libchromatix_imx318_cpp_arcsoft_bokeh \
    libchromatix_imx318_cpp_bokeh \
    libchromatix_imx318_cpp_electron_aperture \
    libchromatix_imx318_cpp_hfr_120 \
    libchromatix_imx318_cpp_hfr_240 \
    libchromatix_imx318_cpp_hfr_60 \
    libchromatix_imx318_cpp_iso128_preview \
    libchromatix_imx318_cpp_iso128_preview_dng \
    libchromatix_imx318_cpp_iso128_snapshot \
    libchromatix_imx318_cpp_iso128_snapshot_dng \
    libchromatix_imx318_cpp_light_painting \
    libchromatix_imx318_cpp_liveshot \
    libchromatix_imx318_cpp_microspur_snapshot \
    libchromatix_imx318_cpp_mtf_denoise \
    libchromatix_imx318_cpp_panorama \
    libchromatix_imx318_cpp_preview \
    libchromatix_imx318_cpp_profession_snapshot \
    libchromatix_imx318_cpp_snapshot \
    libchromatix_imx318_cpp_snapshot_dng \
    libchromatix_imx318_cpp_snapshot_downscale \
    libchromatix_imx318_cpp_snapshot_hdr \
    libchromatix_imx318_cpp_snapshot_upscale \
    libchromatix_imx318_cpp_startrack \
    libchromatix_imx318_cpp_video \
    libchromatix_imx318_cpp_video_4k \
    libchromatix_imx318_cpp_video_hdr \
    libchromatix_imx318_default_preview_3a \
    libchromatix_imx318_default_video \
    libchromatix_imx318_default_video_3a \
    libchromatix_imx318_fullsize_preview_3a \
    libchromatix_imx318_fullsize_preview_3a_dng \
    libchromatix_imx318_fullsize_video_3a \
    libchromatix_imx318_hdr_snapshot_3a \
    libchromatix_imx318_hdr_video_3a \
    libchromatix_imx318_hfr_120 \
    libchromatix_imx318_hfr_120_3a \
    libchromatix_imx318_hfr_240 \
    libchromatix_imx318_hfr_60 \
    libchromatix_imx318_hfr_60_3a \
    libchromatix_imx318_isp_electron_aperture \
    libchromatix_imx318_isp_iso128 \
    libchromatix_imx318_isp_iso128_dng \
    libchromatix_imx318_isp_light_painting \
    libchromatix_imx318_isp_panorama \
    libchromatix_imx318_isp_profession_mode \
    libchromatix_imx318_isp_slowshutter \
    libchromatix_imx318_isp_startrack \
    libchromatix_imx318_postproc \
    libchromatix_imx318_preview \
    libchromatix_imx318_snapshot \
    libchromatix_imx318_snapshot_dng \
    libchromatix_imx318_snapshot_hdr \
    libchromatix_imx318_video_4k \
    libchromatix_imx318_video_hdr \
    libchromatix_imx362_1080p_preview_3a \
    libchromatix_imx362_1080p_video_3a \
    libchromatix_imx362_4k_preview_3a \
    libchromatix_imx362_4k_video_3a \
    libchromatix_imx362_a3_3dtest_mode \
    libchromatix_imx362_a3_elec_aper_hand \
    libchromatix_imx362_a3_electron_aperture \
    libchromatix_imx362_a3_iso128_preview \
    libchromatix_imx362_a3_light_painting \
    libchromatix_imx362_a3_panorama \
    libchromatix_imx362_a3_profession_mode \
    libchromatix_imx362_a3_startrack \
    libchromatix_imx362_auto_slow_shutter \
    libchromatix_imx362_common \
    libchromatix_imx362_common_binning \
    libchromatix_imx362_common_iso128 \
    libchromatix_imx362_cpp_electron_aperture \
    libchromatix_imx362_cpp_hfr_120 \
    libchromatix_imx362_cpp_hfr_240 \
    libchromatix_imx362_cpp_hfr_60 \
    libchromatix_imx362_cpp_iso128_preview \
    libchromatix_imx362_cpp_iso128_snapshot \
    libchromatix_imx362_cpp_light_painting \
    libchromatix_imx362_cpp_liveshot \
    libchromatix_imx362_cpp_microspur_snapshot \
    libchromatix_imx362_cpp_mtf_denoise \
    libchromatix_imx362_cpp_panorama \
    libchromatix_imx362_cpp_preview \
    libchromatix_imx362_cpp_profession_snapshot \
    libchromatix_imx362_cpp_snapshot \
    libchromatix_imx362_cpp_snapshot_downscale \
    libchromatix_imx362_cpp_snapshot_hdr \
    libchromatix_imx362_cpp_snapshot_upscale \
    libchromatix_imx362_cpp_startrack \
    libchromatix_imx362_cpp_video \
    libchromatix_imx362_cpp_video_4k \
    libchromatix_imx362_cpp_video_hdr \
    libchromatix_imx362_default_preview_3a \
    libchromatix_imx362_default_video \
    libchromatix_imx362_default_video_3a \
    libchromatix_imx362_fullsize_preview_3a \
    libchromatix_imx362_fullsize_video_3a \
    libchromatix_imx362_hdr_snapshot_3a \
    libchromatix_imx362_hdr_video_3a \
    libchromatix_imx362_hfr_120 \
    libchromatix_imx362_hfr_120_3a \
    libchromatix_imx362_hfr_240 \
    libchromatix_imx362_hfr_240_3a \
    libchromatix_imx362_hfr_60 \
    libchromatix_imx362_hfr_60_3a \
    libchromatix_imx362_isp_electron_aperture \
    libchromatix_imx362_isp_iso128 \
    libchromatix_imx362_isp_light_painting \
    libchromatix_imx362_isp_panorama \
    libchromatix_imx362_isp_profession_mode \
    libchromatix_imx362_isp_slowshutter \
    libchromatix_imx362_isp_startrack \
    libchromatix_imx362_postproc \
    libchromatix_imx362_preview \
    libchromatix_imx362_snapshot \
    libchromatix_imx362_snapshot_hdr \
    libchromatix_imx362_video_4k \
    libchromatix_imx362_video_hdr \
    libchromatix_s5k3p3_a3_default_preview \
    libchromatix_s5k3p3_a3_default_video \
    libchromatix_s5k3p3_a3_zsl_preview \
    libchromatix_s5k3p3_a3_zsl_video \
    libchromatix_s5k3p3_common \
    libchromatix_s5k3p3_cpp_liveshot \
    libchromatix_s5k3p3_cpp_mtf_denoise \
    libchromatix_s5k3p3_cpp_preview \
    libchromatix_s5k3p3_cpp_snapshot \
    libchromatix_s5k3p3_cpp_video \
    libchromatix_s5k3p3_isp_liveshot \
    libchromatix_s5k3p3_isp_preview \
    libchromatix_s5k3p3_isp_snapshot \
    libchromatix_s5k3p3_isp_video \
    libchromatix_s5k3p3_postproc \
    libdepthmapwrapper \
    libflash_pmic \
    libhal_dbg \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libmm-qcamera \
    libmmcamera2_altek_tube \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_modules \
    libmmcamera_bokeh \
    libmmcamera_depth_map \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_imx318 \
    libmmcamera_imx318_eeprom \
    libmmcamera_imx362 \
    libmmcamera_imx362_eeprom \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_nubiacustpro \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k3p3 \
    libmmcamera_s5k3p3_front_eeprom \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libois_bu63165 \
    libois_lc898122 \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    com.fingerprints.extension@1.0 \
    gatekeeper.msm8998 \
    keystore.msm8998 \
    nfc_nci.msm8998 \
    libAltek_Alignment \
    libArcsoftAlgorithm \
    libDualCamera_Calibration \
    libqfp-service \
    vendor.qti.hardware.fingerprint@1.0 \
    android.hardware.biometrics.fingerprint.fpc@2.1-service \
    mm-qcamera-daemon \
    qfp-daemon
